// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSSFv_wKhHOx577iAFFCTr5QFeelsgkpE',
    appId: '1:212046938458:web:29fe56ad83c840ca63b363',
    messagingSenderId: '212046938458',
    projectId: 'tictactoe-unison',
    authDomain: 'tictactoe-unison.firebaseapp.com',
    storageBucket: 'tictactoe-unison.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsLFtkVgaTxmuxcLMYYxNwv7sfJ2PYQHM',
    appId: '1:212046938458:android:c2435d061e102ad863b363',
    messagingSenderId: '212046938458',
    projectId: 'tictactoe-unison',
    storageBucket: 'tictactoe-unison.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdhq9dcLAAHLVF21VQH_-YqRAEywMytx8',
    appId: '1:212046938458:ios:92f4e7ed39514b3063b363',
    messagingSenderId: '212046938458',
    projectId: 'tictactoe-unison',
    storageBucket: 'tictactoe-unison.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeUnison',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdhq9dcLAAHLVF21VQH_-YqRAEywMytx8',
    appId: '1:212046938458:ios:92f4e7ed39514b3063b363',
    messagingSenderId: '212046938458',
    projectId: 'tictactoe-unison',
    storageBucket: 'tictactoe-unison.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeUnison',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSSFv_wKhHOx577iAFFCTr5QFeelsgkpE',
    appId: '1:212046938458:web:8fdc0b6664537ad363b363',
    messagingSenderId: '212046938458',
    projectId: 'tictactoe-unison',
    authDomain: 'tictactoe-unison.firebaseapp.com',
    storageBucket: 'tictactoe-unison.firebasestorage.app',
  );
}
